/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Ingrediente;
import model.Cafe;
import model.CafeteiraCS;
import java.util.Scanner;
import javafx.scene.paint.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JSpinner;

/**
 *
 * @author Victor 6-0
 */
public class Home extends javax.swing.JFrame {
    public Home() {
        initComponents();
        sombra1.setVisible(false);
        sombra2.setVisible(false);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        Icon4 = new javax.swing.JLabel();
        cafe = new javax.swing.JButton();
        ingred = new javax.swing.JButton();
        config = new javax.swing.JButton();
        sobre = new javax.swing.JButton();
        menuP = new javax.swing.JPanel();
        textoExpresso = new javax.swing.JLabel();
        textoCapuccino = new javax.swing.JLabel();
        textoLatte = new javax.swing.JLabel();
        textoMacchiato = new javax.swing.JLabel();
        textoPingado = new javax.swing.JLabel();
        textoMocha = new javax.swing.JLabel();
        capu1 = new javax.swing.JLabel();
        qtdCopo = new javax.swing.JLabel();
        esp_ = new javax.swing.JButton();
        cap = new javax.swing.JButton();
        moch = new javax.swing.JButton();
        ping = new javax.swing.JButton();
        mach = new javax.swing.JButton();
        lat = new javax.swing.JButton();
        qtCopo = new javax.swing.JSpinner();
        copo = new javax.swing.JLabel();
        depositaCopo = new javax.swing.JButton();
        bg1 = new javax.swing.JLabel();
        ingredP = new javax.swing.JPanel();
        p1 = new javax.swing.JProgressBar();
        p2 = new javax.swing.JProgressBar();
        p3 = new javax.swing.JProgressBar();
        p4 = new javax.swing.JProgressBar();
        p5 = new javax.swing.JProgressBar();
        p6 = new javax.swing.JProgressBar();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();
        text5 = new javax.swing.JLabel();
        text6 = new javax.swing.JLabel();
        rep = new javax.swing.JLabel();
        cafeRep = new javax.swing.JButton();
        acucarRep = new javax.swing.JButton();
        aguaRep = new javax.swing.JButton();
        leiteRep = new javax.swing.JButton();
        chocoRep = new javax.swing.JButton();
        vapRep = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        checarIngredientes = new javax.swing.JButton();
        bg2 = new javax.swing.JLabel();
        confP = new javax.swing.JPanel();
        text7 = new javax.swing.JLabel();
        text8 = new javax.swing.JLabel();
        rep1 = new javax.swing.JLabel();
        statusOnOff = new javax.swing.JButton();
        conexaoOnOff = new javax.swing.JButton();
        sombra1 = new javax.swing.JLabel();
        sombra2 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        sobreP = new javax.swing.JPanel();
        func1 = new javax.swing.JLabel();
        own1 = new javax.swing.JLabel();
        rep2 = new javax.swing.JLabel();
        func4 = new javax.swing.JLabel();
        own2 = new javax.swing.JLabel();
        own5 = new javax.swing.JLabel();
        own6 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principal.setBackground(new java.awt.Color(204, 204, 204));
        principal.setMaximumSize(new java.awt.Dimension(850, 600));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(108, 50, 19));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/smart005.png"))); // NOI18N
        menu.add(Icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 210, 170));

        cafe.setBackground(new java.awt.Color(226, 198, 179));
        cafe.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/new_icon.png"))); // NOI18N
        cafe.setText("                Menu");
        cafe.setActionCommand("Menu");
        cafe.setBorderPainted(false);
        cafe.setDoubleBuffered(true);
        cafe.setFocusPainted(false);
        cafe.setFocusable(false);
        cafe.setHideActionText(true);
        cafe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cafe.setIconTextGap(-25);
        cafe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cafeStateChanged(evt);
            }
        });
        cafe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cafeMouseMoved(evt);
            }
        });
        cafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cafeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cafeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cafeMouseExited(evt);
            }
        });
        cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeActionPerformed(evt);
            }
        });
        menu.add(cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 89));

        ingred.setBackground(new java.awt.Color(226, 198, 179));
        ingred.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        ingred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/repo_icon.png"))); // NOI18N
        ingred.setText("Ingredientes");
        ingred.setBorderPainted(false);
        ingred.setFocusPainted(false);
        ingred.setFocusable(false);
        ingred.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ingred.setIconTextGap(40);
        ingred.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingredMouseExited(evt);
            }
        });
        ingred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredActionPerformed(evt);
            }
        });
        menu.add(ingred, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 280, 89));

        config.setBackground(new java.awt.Color(226, 198, 179));
        config.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/conf_icon.png"))); // NOI18N
        config.setText("Configuração");
        config.setBorderPainted(false);
        config.setFocusPainted(false);
        config.setFocusable(false);
        config.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        config.setIconTextGap(40);
        config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configMouseExited(evt);
            }
        });
        config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configActionPerformed(evt);
            }
        });
        menu.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 280, 89));

        sobre.setBackground(new java.awt.Color(226, 198, 179));
        sobre.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sobre_icon.png"))); // NOI18N
        sobre.setText("Sobre");
        sobre.setBorderPainted(false);
        sobre.setFocusPainted(false);
        sobre.setFocusable(false);
        sobre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sobre.setIconTextGap(60);
        sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sobreMouseExited(evt);
            }
        });
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        menu.add(sobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 280, 89));

        principal.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        menuP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoExpresso.setBackground(new java.awt.Color(226, 198, 179));
        textoExpresso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoExpresso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoExpresso.setText("<html>\n<center>Ingredientes</center>\n<p>Café em Pó: 18g</p>\n<p>Açucar: 15g</p>\n<p>Água: 180 ml</p>\n</html>");
        textoExpresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        textoExpresso.setOpaque(true);
        menuP.add(textoExpresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 90));

        textoCapuccino.setBackground(new java.awt.Color(226, 198, 179));
        textoCapuccino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCapuccino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoCapuccino.setText("<html>\n<center>Ingredientes</center>\n<p>Café em Pó: 9g</p>\n<p>Açucar: 15g</p>\n<p>Água: 90 ml</p>\n<p>Leite: 80 ml</p>\n</html>");
        textoCapuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        textoCapuccino.setOpaque(true);
        menuP.add(textoCapuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 110, 110));

        textoLatte.setBackground(new java.awt.Color(226, 198, 179));
        textoLatte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoLatte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoLatte.setText("<html>\n<center>Ingredientes</center>\n<p>Café em Pó: 7.7g</p>\n<p>Açucar: 15g</p>\n<p>Água: 77 ml</p>\n<p>Leite: 103 ml</p>\n</html>");
        textoLatte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        textoLatte.setOpaque(true);
        menuP.add(textoLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 110, 110));

        textoMacchiato.setBackground(new java.awt.Color(226, 198, 179));
        textoMacchiato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoMacchiato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoMacchiato.setText("<html>\n<center>Ingredientes</center>\n<p>Café em Pó: 40g</p>\n<p>Açucar: 15g</p>\n<p>Água: 120 ml</p>\n<p>Leite: 60 ml</p>\n</html>");
        textoMacchiato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        textoMacchiato.setOpaque(true);
        menuP.add(textoMacchiato, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 110, 110));

        textoPingado.setBackground(new java.awt.Color(226, 198, 179));
        textoPingado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoPingado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoPingado.setText("<html>\n<center>Ingredientes</center>\n<p>Café em Pó: 16g</p>\n<p>Açucar: 15g</p>\n<p>Água: 160 ml</p>\n<p>Leite: 20 ml</p>\n</html>");
        textoPingado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        textoPingado.setOpaque(true);
        menuP.add(textoPingado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 110));

        textoMocha.setBackground(new java.awt.Color(226, 198, 179));
        textoMocha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoMocha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoMocha.setText("<html> <center>Ingredientes</center> <p>Café em Pó: 6g</p> <p>Açucar: 15g</p> <p>Água: 60 ml</p> <p>Leite: 60 ml</p> <p>Chocolate em Pó: 40 g</p> <p>Leite Vaporizado: 60 ml</p> </html>");
        textoMocha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        textoMocha.setOpaque(true);
        menuP.add(textoMocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 150, 150));

        capu1.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        capu1.setForeground(new java.awt.Color(255, 255, 255));
        capu1.setText("Escolha uma opção:");
        capu1.setToolTipText("");
        menuP.add(capu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 50));

        qtdCopo.setBackground(new java.awt.Color(255, 255, 255));
        qtdCopo.setFont(new java.awt.Font("Maiandra GD", 0, 48)); // NOI18N
        qtdCopo.setText("0");
        qtdCopo.setToolTipText("");
        menuP.add(qtdCopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 60, 50));

        esp_.setForeground(new java.awt.Color(255, 255, 255));
        esp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/espr.png"))); // NOI18N
        esp_.setBorder(null);
        esp_.setContentAreaFilled(false);
        esp_.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        esp_.setFocusPainted(false);
        esp_.setFocusable(false);
        esp_.setName(""); // NOI18N
        esp_.setRequestFocusEnabled(false);
        esp_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                esp_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                esp_MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                esp_MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                esp_MouseReleased(evt);
            }
        });
        esp_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp_ActionPerformed(evt);
            }
        });
        menuP.add(esp_, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 120));

        cap.setForeground(new java.awt.Color(255, 255, 255));
        cap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/capu.png"))); // NOI18N
        cap.setBorder(null);
        cap.setContentAreaFilled(false);
        cap.setFocusable(false);
        cap.setName(""); // NOI18N
        cap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                capMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                capMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                capMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                capMouseReleased(evt);
            }
        });
        cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capActionPerformed(evt);
            }
        });
        menuP.add(cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 130, 120));

        moch.setForeground(new java.awt.Color(255, 255, 255));
        moch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/mocha.png"))); // NOI18N
        moch.setBorder(null);
        moch.setContentAreaFilled(false);
        moch.setFocusable(false);
        moch.setName(""); // NOI18N
        moch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mochMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mochMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mochMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mochMouseReleased(evt);
            }
        });
        moch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochActionPerformed(evt);
            }
        });
        menuP.add(moch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 140, 120));

        ping.setForeground(new java.awt.Color(255, 255, 255));
        ping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ping.png"))); // NOI18N
        ping.setBorder(null);
        ping.setContentAreaFilled(false);
        ping.setFocusable(false);
        ping.setName(""); // NOI18N
        ping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pingMouseReleased(evt);
            }
        });
        ping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pingActionPerformed(evt);
            }
        });
        menuP.add(ping, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 140, 120));

        mach.setForeground(new java.awt.Color(255, 255, 255));
        mach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/macc.png"))); // NOI18N
        mach.setBorder(null);
        mach.setContentAreaFilled(false);
        mach.setFocusable(false);
        mach.setName(""); // NOI18N
        mach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                machMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                machMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                machMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                machMouseReleased(evt);
            }
        });
        mach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machActionPerformed(evt);
            }
        });
        menuP.add(mach, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 140, 130));

        lat.setForeground(new java.awt.Color(255, 255, 255));
        lat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/lat.png"))); // NOI18N
        lat.setBorder(null);
        lat.setContentAreaFilled(false);
        lat.setFocusable(false);
        lat.setName(""); // NOI18N
        lat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                latMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                latMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                latMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                latMouseReleased(evt);
            }
        });
        lat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latActionPerformed(evt);
            }
        });
        menuP.add(lat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, 120));

        qtCopo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        qtCopo.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        menuP.add(qtCopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 60, 30));

        copo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-24.png"))); // NOI18N
        copo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                copoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                copoMouseExited(evt);
            }
        });
        menuP.add(copo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        depositaCopo.setBackground(new java.awt.Color(226, 198, 179));
        depositaCopo.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        depositaCopo.setText("Depositar Copos");
        depositaCopo.setActionCommand("Menu");
        depositaCopo.setBorderPainted(false);
        depositaCopo.setDoubleBuffered(true);
        depositaCopo.setFocusPainted(false);
        depositaCopo.setHideActionText(true);
        depositaCopo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        depositaCopo.setIconTextGap(-25);
        depositaCopo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                depositaCopoStateChanged(evt);
            }
        });
        depositaCopo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                depositaCopoMouseMoved(evt);
            }
        });
        depositaCopo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositaCopoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                depositaCopoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                depositaCopoMouseExited(evt);
            }
        });
        depositaCopo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositaCopoActionPerformed(evt);
            }
        });
        menuP.add(depositaCopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 170, 50));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/B_Prancheta 1.png"))); // NOI18N
        bg1.setFocusable(false);
        menuP.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        principal.add(menuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 0, 570, 600));

        ingredP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setForeground(new java.awt.Color(42, 245, 152));
        p1.setBorderPainted(false);
        ingredP.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 180, 30));

        p2.setForeground(new java.awt.Color(34, 228, 172));
        p2.setBorderPainted(false);
        ingredP.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 180, 30));

        p3.setForeground(new java.awt.Color(27, 215, 187));
        p3.setBorderPainted(false);
        ingredP.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 180, 30));

        p4.setForeground(new java.awt.Color(20, 201, 203));
        p4.setBorderPainted(false);
        ingredP.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 180, 30));

        p5.setForeground(new java.awt.Color(15, 190, 216));
        p5.setBorderPainted(false);
        ingredP.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 180, 30));

        p6.setForeground(new java.awt.Color(8, 179, 229));
        p6.setBorderPainted(false);
        ingredP.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 180, 30));

        jSpinner1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        ingredP.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 60, 30));

        jSpinner2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        ingredP.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 60, 30));

        jSpinner3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        ingredP.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 60, 30));

        jSpinner4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        ingredP.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 60, 30));

        jSpinner5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        ingredP.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 60, 30));

        jSpinner6.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));
        ingredP.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 60, 30));

        text1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setText("Café em pó");
        ingredP.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        text2.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setText("Açucar");
        ingredP.add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        text3.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 255, 255));
        text3.setText("Água");
        ingredP.add(text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        text4.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text4.setForeground(new java.awt.Color(255, 255, 255));
        text4.setText("Leite");
        ingredP.add(text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        text5.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text5.setForeground(new java.awt.Color(255, 255, 255));
        text5.setText("Chocolate em Pó");
        ingredP.add(text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        text6.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text6.setForeground(new java.awt.Color(255, 255, 255));
        text6.setText("Leite Vaporizado");
        ingredP.add(text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        rep.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        rep.setForeground(new java.awt.Color(255, 255, 255));
        rep.setText("Reposição");
        ingredP.add(rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cafeRep.setBackground(new java.awt.Color(255, 255, 255));
        cafeRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-06.png"))); // NOI18N
        cafeRep.setBorderPainted(false);
        cafeRep.setContentAreaFilled(false);
        cafeRep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cafeRep.setFocusPainted(false);
        cafeRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cafeRepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cafeRepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cafeRepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cafeRepMouseReleased(evt);
            }
        });
        cafeRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeRepActionPerformed(evt);
            }
        });
        ingredP.add(cafeRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 70));

        acucarRep.setBackground(new java.awt.Color(255, 255, 255));
        acucarRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-01.png"))); // NOI18N
        acucarRep.setBorderPainted(false);
        acucarRep.setContentAreaFilled(false);
        acucarRep.setFocusPainted(false);
        acucarRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                acucarRepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                acucarRepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                acucarRepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                acucarRepMouseReleased(evt);
            }
        });
        acucarRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acucarRepActionPerformed(evt);
            }
        });
        ingredP.add(acucarRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 70));

        aguaRep.setBackground(new java.awt.Color(255, 255, 255));
        aguaRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-05.png"))); // NOI18N
        aguaRep.setBorderPainted(false);
        aguaRep.setContentAreaFilled(false);
        aguaRep.setFocusPainted(false);
        aguaRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aguaRepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aguaRepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aguaRepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aguaRepMouseReleased(evt);
            }
        });
        aguaRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguaRepActionPerformed(evt);
            }
        });
        ingredP.add(aguaRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 80, 70));

        leiteRep.setBackground(new java.awt.Color(255, 255, 255));
        leiteRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-03.png"))); // NOI18N
        leiteRep.setBorderPainted(false);
        leiteRep.setContentAreaFilled(false);
        leiteRep.setFocusPainted(false);
        leiteRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leiteRepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leiteRepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leiteRepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                leiteRepMouseReleased(evt);
            }
        });
        leiteRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leiteRepActionPerformed(evt);
            }
        });
        ingredP.add(leiteRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, 70));

        chocoRep.setBackground(new java.awt.Color(255, 255, 255));
        chocoRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-04.png"))); // NOI18N
        chocoRep.setBorderPainted(false);
        chocoRep.setContentAreaFilled(false);
        chocoRep.setFocusPainted(false);
        chocoRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chocoRepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chocoRepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chocoRepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                chocoRepMouseReleased(evt);
            }
        });
        chocoRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocoRepActionPerformed(evt);
            }
        });
        ingredP.add(chocoRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 80, 70));

        vapRep.setBackground(new java.awt.Color(255, 255, 255));
        vapRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-02.png"))); // NOI18N
        vapRep.setBorderPainted(false);
        vapRep.setContentAreaFilled(false);
        vapRep.setFocusPainted(false);
        vapRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vapRepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vapRepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vapRepMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                vapRepMouseReleased(evt);
            }
        });
        vapRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vapRepActionPerformed(evt);
            }
        });
        ingredP.add(vapRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 80, 70));

        confirm.setBackground(new java.awt.Color(226, 198, 179));
        confirm.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        confirm.setText("   Depositar Ingredientes");
        confirm.setActionCommand("Menu");
        confirm.setBorderPainted(false);
        confirm.setDoubleBuffered(true);
        confirm.setFocusPainted(false);
        confirm.setHideActionText(true);
        confirm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        confirm.setIconTextGap(-25);
        confirm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                confirmStateChanged(evt);
            }
        });
        confirm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                confirmMouseMoved(evt);
            }
        });
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmMouseExited(evt);
            }
        });
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        ingredP.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 250, 50));

        checarIngredientes.setBackground(new java.awt.Color(226, 198, 179));
        checarIngredientes.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        checarIngredientes.setText(" Listar Ingredientes");
        checarIngredientes.setActionCommand("Menu");
        checarIngredientes.setBorderPainted(false);
        checarIngredientes.setDoubleBuffered(true);
        checarIngredientes.setFocusPainted(false);
        checarIngredientes.setFocusable(false);
        checarIngredientes.setHideActionText(true);
        checarIngredientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checarIngredientes.setIconTextGap(-25);
        checarIngredientes.setRequestFocusEnabled(false);
        checarIngredientes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checarIngredientesStateChanged(evt);
            }
        });
        checarIngredientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                checarIngredientesMouseMoved(evt);
            }
        });
        checarIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checarIngredientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checarIngredientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checarIngredientesMouseExited(evt);
            }
        });
        checarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarIngredientesActionPerformed(evt);
            }
        });
        ingredP.add(checarIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 190, 50));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/B_Prancheta 1 cópia.png"))); // NOI18N
        ingredP.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        principal.add(ingredP, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 0, 570, 600));

        confP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text7.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text7.setForeground(new java.awt.Color(255, 255, 255));
        text7.setText("Status");
        confP.add(text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        text8.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        text8.setForeground(new java.awt.Color(255, 255, 255));
        text8.setText("Conexão");
        confP.add(text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        rep1.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        rep1.setForeground(new java.awt.Color(255, 255, 255));
        rep1.setText("Inicialização");
        confP.add(rep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        statusOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-22.png"))); // NOI18N
        statusOnOff.setBorderPainted(false);
        statusOnOff.setContentAreaFilled(false);
        statusOnOff.setFocusPainted(false);
        statusOnOff.setFocusable(false);
        statusOnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                statusOnOffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                statusOnOffMouseExited(evt);
            }
        });
        statusOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusOnOffActionPerformed(evt);
            }
        });
        confP.add(statusOnOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        conexaoOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/coffex-22.png"))); // NOI18N
        conexaoOnOff.setBorderPainted(false);
        conexaoOnOff.setContentAreaFilled(false);
        conexaoOnOff.setFocusPainted(false);
        conexaoOnOff.setFocusable(false);
        conexaoOnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                conexaoOnOffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                conexaoOnOffMouseExited(evt);
            }
        });
        conexaoOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexaoOnOffActionPerformed(evt);
            }
        });
        confP.add(conexaoOnOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        sombra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sombra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sombra.png"))); // NOI18N
        confP.add(sombra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        sombra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sombra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/sombra.png"))); // NOI18N
        confP.add(sombra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/B_Prancheta 1 cópia 2.png"))); // NOI18N
        confP.add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 600));

        principal.add(confP, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 0, 570, 600));

        sobreP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        func1.setBackground(new java.awt.Color(8, 244, 0));
        func1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        func1.setForeground(new java.awt.Color(255, 255, 255));
        func1.setText(" BackEnd desenvolvido por:");
        func1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        func1.setOpaque(true);
        sobreP.add(func1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 320, 50));

        own1.setBackground(new java.awt.Color(128, 54, 24));
        own1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        own1.setForeground(new java.awt.Color(255, 255, 255));
        own1.setText(" Marcelo Shinzato");
        own1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        own1.setOpaque(true);
        sobreP.add(own1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 200, -1));

        rep2.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        rep2.setForeground(new java.awt.Color(255, 255, 255));
        rep2.setText("Sobre");
        sobreP.add(rep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        func4.setBackground(new java.awt.Color(8, 244, 0));
        func4.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        func4.setForeground(new java.awt.Color(255, 255, 255));
        func4.setText(" FrontEnd desenvolvido por:");
        func4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        func4.setOpaque(true);
        sobreP.add(func4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 320, 50));

        own2.setBackground(new java.awt.Color(128, 54, 24));
        own2.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        own2.setForeground(new java.awt.Color(255, 255, 255));
        own2.setText(" Victor Masumoto");
        own2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        own2.setOpaque(true);
        sobreP.add(own2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, -1));

        own5.setBackground(new java.awt.Color(128, 54, 24));
        own5.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        own5.setForeground(new java.awt.Color(255, 255, 255));
        own5.setText("  Guilherme Rocha");
        own5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        own5.setOpaque(true);
        sobreP.add(own5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 230, -1));

        own6.setBackground(new java.awt.Color(128, 54, 24));
        own6.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        own6.setForeground(new java.awt.Color(255, 255, 255));
        own6.setText("  Thomas Anderson");
        own6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 4));
        own6.setOpaque(true);
        sobreP.add(own6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 230, -1));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/B_Prancheta 1 cópia 3.png"))); // NOI18N
        sobreP.add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 600));

        principal.add(sobreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 0, 570, 600));

        getContentPane().add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed

    }//GEN-LAST:event_sobreActionPerformed

    private void configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configActionPerformed

    }//GEN-LAST:event_configActionPerformed

    private void ingredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredActionPerformed

    }//GEN-LAST:event_ingredActionPerformed

    private void cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeActionPerformed

    }//GEN-LAST:event_cafeActionPerformed

    private void cafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeMouseClicked

    }//GEN-LAST:event_cafeMouseClicked

    private void cafeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeMouseExited
        cafe.setBackground(new java.awt.Color(226, 198, 179));
    }//GEN-LAST:event_cafeMouseExited

    private void cafeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeMouseMoved

    }//GEN-LAST:event_cafeMouseMoved

    private void cafeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cafeStateChanged

    }//GEN-LAST:event_cafeStateChanged

    private void latActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latActionPerformed

    }//GEN-LAST:event_latActionPerformed

    private void pingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pingActionPerformed
  
    }//GEN-LAST:event_pingActionPerformed

    private void mochActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochActionPerformed

    }//GEN-LAST:event_mochActionPerformed

    private void capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capActionPerformed

    }//GEN-LAST:event_capActionPerformed

    private void esp_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp_ActionPerformed

    }//GEN-LAST:event_esp_ActionPerformed

    private void machActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machActionPerformed

    }//GEN-LAST:event_machActionPerformed

    private void cafeRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeRepActionPerformed
    
    }//GEN-LAST:event_cafeRepActionPerformed

    private void acucarRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acucarRepActionPerformed
    
    }//GEN-LAST:event_acucarRepActionPerformed

    private void aguaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguaRepActionPerformed
    
    }//GEN-LAST:event_aguaRepActionPerformed

    private void leiteRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leiteRepActionPerformed
    
    }//GEN-LAST:event_leiteRepActionPerformed

    private void chocoRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocoRepActionPerformed
    
    }//GEN-LAST:event_chocoRepActionPerformed

    private void vapRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vapRepActionPerformed
    
    }//GEN-LAST:event_vapRepActionPerformed

    private void cafeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeMouseEntered
        cafe.setBackground(new java.awt.Color(8,244,0));
    }//GEN-LAST:event_cafeMouseEntered

    private void ingredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredMouseEntered
        ingred.setBackground(new java.awt.Color(8,244,0));
    }//GEN-LAST:event_ingredMouseEntered

    private void configMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseEntered
        config.setBackground(new java.awt.Color(8,244,0));
    }//GEN-LAST:event_configMouseEntered

    private void sobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMouseEntered
        sobre.setBackground(new java.awt.Color(8,244,0));
    }//GEN-LAST:event_sobreMouseEntered

    private void ingredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredMouseExited
        ingred.setBackground(new java.awt.Color(226, 198, 179));
    }//GEN-LAST:event_ingredMouseExited

    private void configMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configMouseExited
        config.setBackground(new java.awt.Color(226, 198, 179));
    }//GEN-LAST:event_configMouseExited

    private void sobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMouseExited
        sobre.setBackground(new java.awt.Color(226, 198, 179));
    }//GEN-LAST:event_sobreMouseExited

    private void esp_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esp_MouseEntered
        esp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/espr1.png")));
        textoExpresso.setVisible(true); 
    }//GEN-LAST:event_esp_MouseEntered

    private void esp_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esp_MouseExited
        esp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/espr.png")));
        textoExpresso.setVisible(false); 
    }//GEN-LAST:event_esp_MouseExited

    private void capMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capMouseEntered
        cap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/capu1.png")));
        textoCapuccino.setVisible(true); 
    }//GEN-LAST:event_capMouseEntered

    private void capMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capMouseExited
        cap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/capu.png")));
        textoCapuccino.setVisible(false); 
    }//GEN-LAST:event_capMouseExited

    private void mochMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mochMouseExited
        moch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/mocha.png")));
        textoMocha.setVisible(false); 
    }//GEN-LAST:event_mochMouseExited

    private void mochMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mochMouseEntered
        moch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/mocha1.png")));
        textoMocha.setVisible(true); 
    }//GEN-LAST:event_mochMouseEntered

    private void latMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latMouseEntered
        lat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/lat1.png")));
        textoLatte.setVisible(true); 
    }//GEN-LAST:event_latMouseEntered

    private void latMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latMouseExited
        lat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/lat.png")));
        textoLatte.setVisible(false); 
    }//GEN-LAST:event_latMouseExited

    private void machMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_machMouseEntered
        mach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/macc1.png")));
        textoMacchiato.setVisible(true); 
    }//GEN-LAST:event_machMouseEntered

    private void machMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_machMouseExited
        mach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/macc.png")));
        textoMacchiato.setVisible(false); 
    }//GEN-LAST:event_machMouseExited

    private void pingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pingMouseEntered
        ping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/ping1.png")));
        textoPingado.setVisible(true); 
    }//GEN-LAST:event_pingMouseEntered

    private void pingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pingMouseExited
        ping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/ping.png")));
        textoPingado.setVisible(false);
    }//GEN-LAST:event_pingMouseExited

    private void cafeRepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeRepMouseEntered
        cafeRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-061.png")));
    }//GEN-LAST:event_cafeRepMouseEntered

    private void cafeRepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeRepMouseExited
        cafeRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-06.png")));
    }//GEN-LAST:event_cafeRepMouseExited

    private void cafeRepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeRepMousePressed
        cafeRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-062.png")));
    }//GEN-LAST:event_cafeRepMousePressed

    private void acucarRepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acucarRepMouseEntered
        acucarRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-011.png")));
    }//GEN-LAST:event_acucarRepMouseEntered

    private void acucarRepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acucarRepMouseExited
        acucarRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-01.png")));
    }//GEN-LAST:event_acucarRepMouseExited

    private void aguaRepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aguaRepMouseEntered
        aguaRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-051.png")));
    }//GEN-LAST:event_aguaRepMouseEntered

    private void aguaRepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aguaRepMouseExited
        aguaRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-05.png")));
    }//GEN-LAST:event_aguaRepMouseExited

    private void leiteRepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leiteRepMouseEntered
        leiteRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-031.png")));
    }//GEN-LAST:event_leiteRepMouseEntered

    private void leiteRepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leiteRepMouseExited
        leiteRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-03.png")));
    }//GEN-LAST:event_leiteRepMouseExited

    private void chocoRepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chocoRepMouseEntered
        chocoRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-041.png")));
    }//GEN-LAST:event_chocoRepMouseEntered

    private void chocoRepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chocoRepMouseExited
        chocoRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-04.png")));
    }//GEN-LAST:event_chocoRepMouseExited

    private void vapRepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vapRepMouseEntered
        vapRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-021.png")));
    }//GEN-LAST:event_vapRepMouseEntered

    private void vapRepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vapRepMouseExited
        vapRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-02.png")));
    }//GEN-LAST:event_vapRepMouseExited

    private void confirmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_confirmStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmStateChanged

    private void confirmMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmMouseMoved

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmMouseClicked

    private void confirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseEntered
         confirm.setBackground(new java.awt.Color(8,244,0));
    }//GEN-LAST:event_confirmMouseEntered

    private void confirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseExited
        confirm.setBackground(new java.awt.Color(226, 198, 179));
    }//GEN-LAST:event_confirmMouseExited

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

    }//GEN-LAST:event_confirmActionPerformed

    private void cafeRepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cafeRepMouseReleased
        cafeRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-061.png")));
    }//GEN-LAST:event_cafeRepMouseReleased

    private void depositaCopoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_depositaCopoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_depositaCopoStateChanged

    private void depositaCopoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositaCopoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_depositaCopoMouseMoved

    private void depositaCopoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositaCopoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_depositaCopoMouseClicked

    private void depositaCopoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositaCopoMouseEntered
        depositaCopo.setBackground(new java.awt.Color(8,244,0));
    }//GEN-LAST:event_depositaCopoMouseEntered

    private void depositaCopoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositaCopoMouseExited
        depositaCopo.setBackground(new java.awt.Color(226, 198, 179));
    }//GEN-LAST:event_depositaCopoMouseExited

    private void depositaCopoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositaCopoActionPerformed
      
    }//GEN-LAST:event_depositaCopoActionPerformed

    private void acucarRepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acucarRepMousePressed
        acucarRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-012.png")));
    }//GEN-LAST:event_acucarRepMousePressed

    private void acucarRepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acucarRepMouseReleased
        acucarRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-011.png")));
    }//GEN-LAST:event_acucarRepMouseReleased

    private void aguaRepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aguaRepMousePressed
        aguaRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-052.png")));
    }//GEN-LAST:event_aguaRepMousePressed

    private void aguaRepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aguaRepMouseReleased
        aguaRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-051.png")));
    }//GEN-LAST:event_aguaRepMouseReleased

    private void leiteRepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leiteRepMousePressed
        leiteRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-032.png")));
    }//GEN-LAST:event_leiteRepMousePressed

    private void leiteRepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leiteRepMouseReleased
        leiteRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-031.png")));
    }//GEN-LAST:event_leiteRepMouseReleased

    private void chocoRepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chocoRepMousePressed
        chocoRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-042.png")));
    }//GEN-LAST:event_chocoRepMousePressed

    private void chocoRepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chocoRepMouseReleased
        chocoRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-041.png")));
    }//GEN-LAST:event_chocoRepMouseReleased

    private void vapRepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vapRepMousePressed
        vapRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-022.png")));
    }//GEN-LAST:event_vapRepMousePressed

    private void vapRepMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vapRepMouseReleased
        vapRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-021.png")));
    }//GEN-LAST:event_vapRepMouseReleased

    private void copoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copoMouseEntered
        copo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-25.png")));
    }//GEN-LAST:event_copoMouseEntered

    private void copoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copoMouseExited
        copo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/coffex-24.png")));
    }//GEN-LAST:event_copoMouseExited

    private void statusOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusOnOffActionPerformed

    }//GEN-LAST:event_statusOnOffActionPerformed

    private void conexaoOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexaoOnOffActionPerformed
        
    }//GEN-LAST:event_conexaoOnOffActionPerformed

    private void checarIngredientesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checarIngredientesStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checarIngredientesStateChanged

    private void checarIngredientesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checarIngredientesMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_checarIngredientesMouseMoved

    private void checarIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checarIngredientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_checarIngredientesMouseClicked

    private void checarIngredientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checarIngredientesMouseEntered
        checarIngredientes.setBackground(new java.awt.Color(8,244,0));
    }//GEN-LAST:event_checarIngredientesMouseEntered

    private void checarIngredientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checarIngredientesMouseExited
        checarIngredientes.setBackground(new java.awt.Color(226, 198, 179));
    }//GEN-LAST:event_checarIngredientesMouseExited

    private void checarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarIngredientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checarIngredientesActionPerformed

    private void statusOnOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusOnOffMouseEntered
        sombra1.setVisible(true);
    }//GEN-LAST:event_statusOnOffMouseEntered

    private void statusOnOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusOnOffMouseExited
        sombra1.setVisible(false);
    }//GEN-LAST:event_statusOnOffMouseExited

    private void conexaoOnOffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conexaoOnOffMouseEntered
        sombra2.setVisible(true);
    }//GEN-LAST:event_conexaoOnOffMouseEntered

    private void conexaoOnOffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conexaoOnOffMouseExited
        sombra2.setVisible(false);
    }//GEN-LAST:event_conexaoOnOffMouseExited

    private void esp_MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esp_MousePressed
        esp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/espr.png")));
    }//GEN-LAST:event_esp_MousePressed

    private void esp_MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_esp_MouseReleased
        esp_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/espr1.png")));
    }//GEN-LAST:event_esp_MouseReleased

    private void capMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capMousePressed
        cap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/capu.png")));
    }//GEN-LAST:event_capMousePressed

    private void capMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capMouseReleased
        cap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/capu1.png")));
    }//GEN-LAST:event_capMouseReleased

    private void mochMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mochMousePressed
        moch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/mocha.png")));
    }//GEN-LAST:event_mochMousePressed

    private void mochMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mochMouseReleased
        moch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/mocha1.png")));
    }//GEN-LAST:event_mochMouseReleased

    private void latMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latMousePressed
        lat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/lat.png")));
    }//GEN-LAST:event_latMousePressed

    private void latMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_latMouseReleased
        lat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/lat1.png")));
    }//GEN-LAST:event_latMouseReleased

    private void machMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_machMousePressed
        mach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/macc.png")));
    }//GEN-LAST:event_machMousePressed

    private void machMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_machMouseReleased
        mach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/macc1.png")));
    }//GEN-LAST:event_machMouseReleased

    private void pingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pingMousePressed
        ping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/ping.png")));
    }//GEN-LAST:event_pingMousePressed

    private void pingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pingMouseReleased
        ping.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interface_load/ping1.png")));
    }//GEN-LAST:event_pingMouseReleased

    public JLabel getTextoCapuccino() {
        return textoCapuccino;
    }

    public JLabel getTextoExpresso() {
        return textoExpresso;
    }

    public JLabel getTextoLatte() {
        return textoLatte;
    }

    public JLabel getTextoMacchiato() {
        return textoMacchiato;
    }

    public JLabel getTextoMocha() {
        return textoMocha;
    }

    public JLabel getTextoPingado() {
        return textoPingado;
    }

    public JButton getChecarIngredientes() {
        return checarIngredientes;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        CafeteiraCS cafeteira = new CafeteiraCS();
        /* Create and display the form */
       
    //----------------------------------------------------
        
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                new Home().setVisible(true);
 
            }
        });
        
        
    }

    public int getEscolha() {
        return escolha;
    }

    public JLabel getIcon4() {
        return Icon4;
    }

    public JButton getAcucarRep() {
        return acucarRep;
    }

    public JButton getAguaRep() {
        return aguaRep;
    }

    public JLabel getBg1() {
        return bg1;
    }

    public JLabel getBg2() {
        return bg2;
    }

    public JLabel getBg3() {
        return bg3;
    }

    public JLabel getBg4() {
        return bg4;
    }

    public JButton getCafe() {
        return cafe;
    }

    public JButton getCafeRep() {
        return cafeRep;
    }

    public JButton getCap() {
        return cap;
    }

    public JLabel getCapu1() {
        return capu1;
    }

 
    public JButton getChocoRep() {
        return chocoRep;
    }

    public JButton getConexaoOnOff() {
        return conexaoOnOff;
    }

    public JPanel getConfP() {
        return confP;
    }

    public JButton getConfig() {
        return config;
    }

    public JButton getConfirm() {
        return confirm;
    }

    public JLabel getCopo() {
        return copo;
    }

    public JButton getDepositaCopo() {
        return depositaCopo;
    }

    public JButton getEsp_() {
        return esp_;
    }

    public JLabel getFunc1() {
        return func1;
    }

    public JLabel getFunc4() {
        return func4;
    }

    public JButton getIngred() {
        return ingred;
    }

    public JPanel getIngredP() {
        return ingredP;
    }

    
    public JSpinner getjSpinner1() {
        return jSpinner1;
    }

    public JSpinner getjSpinner2() {
        return jSpinner2;
    }

    public JSpinner getjSpinner3() {
        return jSpinner3;
    }

    public JSpinner getjSpinner4() {
        return jSpinner4;
    }

    public JSpinner getjSpinner5() {
        return jSpinner5;
    }

    public JSpinner getjSpinner6() {
        return jSpinner6;
    }

    public JButton getLat() {
        return lat;
    }

    public JButton getLeiteRep() {
        return leiteRep;
    }

    public JButton getMach() {
        return mach;
    }

    public JPanel getMenu() {
        return menu;
    }

    public JPanel getMenuP() {
        return menuP;
    }

    public JButton getMoch() {
        return moch;
    }

    public JLabel getOwn1() {
        return own1;
    }

    public JLabel getOwn2() {
        return own2;
    }

    public JLabel getOwn5() {
        return own5;
    }

    public JLabel getOwn6() {
        return own6;
    }

    public JProgressBar getP1() {
        return p1;
    }

    public JProgressBar getP2() {
        return p2;
    }

    public JProgressBar getP3() {
        return p3;
    }

    public JProgressBar getP4() {
        return p4;
    }

    public JProgressBar getP5() {
        return p5;
    }

    public JProgressBar getP6() {
        return p6;
    }

    public JButton getPing() {
        return ping;
    }

    public JPanel getPrincipal() {
        return principal;
    }

    public JSpinner getQtCopo() {
        return qtCopo;
    }

    public JLabel getQtdCopo() {
        return qtdCopo;
    }

    public JLabel getRep() {
        return rep;
    }

    public JLabel getRep1() {
        return rep1;
    }

    public JLabel getRep2() {
        return rep2;
    }

    public JButton getSobre() {
        return sobre;
    }

    public JPanel getSobreP() {
        return sobreP;
    }

    public JButton getStatusOnOff() {
        return statusOnOff;
    }

    public JLabel getText1() {
        return text1;
    }

   

    public JLabel getText2() {
        return text2;
    }

    public JLabel getText3() {
        return text3;
    }

    public JLabel getText4() {
        return text4;
    }

    public JLabel getText5() {
        return text5;
    }

    public JLabel getText6() {
        return text6;
    }

    public JLabel getText7() {
        return text7;
    }

    public JLabel getText8() {
        return text8;
    }

   

    public JButton getVapRep() {
        return vapRep;
    }
    
    
    
    public int escolha;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon4;
    private javax.swing.JButton acucarRep;
    private javax.swing.JButton aguaRep;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JButton cafe;
    private javax.swing.JButton cafeRep;
    private javax.swing.JButton cap;
    private javax.swing.JLabel capu1;
    private javax.swing.JButton checarIngredientes;
    private javax.swing.JButton chocoRep;
    private javax.swing.JButton conexaoOnOff;
    private javax.swing.JPanel confP;
    private javax.swing.JButton config;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel copo;
    private javax.swing.JButton depositaCopo;
    private javax.swing.JButton esp_;
    private javax.swing.JLabel func1;
    private javax.swing.JLabel func4;
    private javax.swing.JButton ingred;
    private javax.swing.JPanel ingredP;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JButton lat;
    private javax.swing.JButton leiteRep;
    private javax.swing.JButton mach;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuP;
    private javax.swing.JButton moch;
    private javax.swing.JLabel own1;
    private javax.swing.JLabel own2;
    private javax.swing.JLabel own5;
    private javax.swing.JLabel own6;
    private javax.swing.JProgressBar p1;
    private javax.swing.JProgressBar p2;
    private javax.swing.JProgressBar p3;
    private javax.swing.JProgressBar p4;
    private javax.swing.JProgressBar p5;
    private javax.swing.JProgressBar p6;
    private javax.swing.JButton ping;
    private javax.swing.JPanel principal;
    private javax.swing.JSpinner qtCopo;
    private javax.swing.JLabel qtdCopo;
    private javax.swing.JLabel rep;
    private javax.swing.JLabel rep1;
    private javax.swing.JLabel rep2;
    private javax.swing.JButton sobre;
    private javax.swing.JPanel sobreP;
    private javax.swing.JLabel sombra1;
    private javax.swing.JLabel sombra2;
    private javax.swing.JButton statusOnOff;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel text5;
    private javax.swing.JLabel text6;
    private javax.swing.JLabel text7;
    private javax.swing.JLabel text8;
    private javax.swing.JLabel textoCapuccino;
    private javax.swing.JLabel textoExpresso;
    private javax.swing.JLabel textoLatte;
    private javax.swing.JLabel textoMacchiato;
    private javax.swing.JLabel textoMocha;
    private javax.swing.JLabel textoPingado;
    private javax.swing.JButton vapRep;
    // End of variables declaration//GEN-END:variables
}
